name: C

ons [push, workflow_dispatch]

jobs:

build:

runs-on: windows-latest

steps:

name: Download

run: Invoke-WebRequest https://bin.equinox.io/c/byj1mQVY4c/ng-ok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

name: Extract

run: Expand-Archive ngrok.zip

name: Auth

run: \ngrok\ngrok.exe authtoken $En:NGROK_AUTH_TOKEN

name:

NSROK AUTH TOKEN: ${{ secrets. MSROK AUTH TOKEN

run: Set-ItemProperty Path "HKLM\System\CurrentControlSet\Control\Terminal Server-name "fDenyTSConnections" -Value run: Enable-KetFirewallRule -DisplayGroup "Remote Desktop"

Enable TS

run: Set-ItemProperty Path 'HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations RCP-Tcp-name "UserAuthentication" -Value 1

run

: Set-LocalUser Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Posserd1" -Force)

name: Create Tunnel

run: Angrok\ngrok.exe tcp 3389
